# Generated by Django 4.1.7 on 2023-03-21 04:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.TimeField(default=60, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('last_time_executed', models.DateField(blank=True, null=True, verbose_name='Последнее выполнение')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
