# Generated by Django 4.1.7 on 2023-03-22 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='execution_time',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение'),
        ),
    ]
